# Generated by Django 2.2 on 2022-06-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.CharField(max_length=2000)),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=50)),
                ('Difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=2000)),
                ('Output', models.CharField(max_length=2000)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojapp.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verdict', models.CharField(max_length=50)),
                ('SubmittedAt', models.DateTimeField(verbose_name='Date and Time Submitted')),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojapp.Problem')),
            ],
        ),
    ]
